include ./config.0.mk
include ./config.1.mk

INTERNALCCFLAGS := -pipe -std=gnu99 -ffreestanding -O2 -Wall -Wextra -pedantic -Werror
INTERNALCPFLAGS := -nostdinc
INTERNALLDFLAGS := -nostdlib -T ./link.ld -static

CC := $(GCC)

CCFLAGS += $(INTERNALCCFLAGS)
CPFLAGS += $(INTERNALCPFLAGS)
LDFLAGS += $(INTERNALLDFLAGS)

SOURCES :=
CLEAN_LIST :=
TREE := .

define add_subdir
    TREE := $$(TREE)/$(1)

    sources_y :=
    clean_list_tree_y :=
	clean_list_root_y :=
    subdirs_y :=

    include $$(TREE)/Makefile

    SOURCES += $$(patsubst %,$$(TREE)/%,$$(sources_y))
    CLEAN_LIST += $$(patsubst %,$$(TREE)/%,$$(clean_list_tree_y))
	CLEAN_LIST += $$(clean_list_root_y)

    $$(foreach subdir,$$(subdirs_y),$$(eval $$(call add_subdir,$$(subdir))))

    TREE := $$(patsubst %/$(1),%,$$(TREE))
endef

BINARY := demos-$(VERSION).$(ARCH).elf
CLEAN_LIST += $(BINARY)

$(eval $(call add_subdir,$(ARCHDIR)))
$(eval $(call add_subdir,lib))
$(eval $(call add_subdir,sys))

OBJECTS := $(SOURCES:=.o)
CLEAN_LIST += $(OBJECTS)

.phony: all kernel clean soft_clean

all: kernel

kernel: $(BINARY)

clean: soft_clean
	@$(foreach item,$(HARD_CLEAN_LIST),echo "rm -f $(item)";rm -f $(item);)

# Soft clean means that we clean only object files
# and other things generated by MAKE and not configure script
soft_clean:
	@$(foreach item,$(CLEAN_LIST),echo "rm -f $(item)";rm -f $(item);)

$(BINARY): $(OBJECTS)
	$(CC) $(CCFLAGS) $(LDFLAGS) $(OBJECTS) -static-libgcc -lgcc -o $(BINARY)

$(OBJECTS): $(SOURCES)
	$(CC) $(CCFLAGS) $(CPFLAGS) -c -o $@ $*
