/* SPDX-License-Identifier: BSD-2-Clause */
#ifndef _SYS_INITCALL_H_
#define _SYS_INITCALL_H_ 1
#include <sys/cdefs.h>

typedef int(*initcall_t)(void);

#define initcall_extr(id) \
    int __initcall_##id(void)

#define initcall_link(id, fn) \
    int __initcall_##id(void) __alias(fn)

/* If an initcall depends on an another initcall,
 * the build system will guarantee that the dependent
 * will be called only after the dependency. */
#define initcall_depn(id, dp) \
    static const initcall_t __used __section(".discard.init.test") \
        __concat(__test_initcall, __COUNTER__) = &__initcall_##dp, \
        __concat(__test_initcall, __COUNTER__) = &__initcall_##id; \
    static const char __used __section(".discard.init.depn") __aligned(1) \
        __concat(__depn_initcall, __COUNTER__)[] = #dp " " #id

/* TODO: add more stub initcalls */
initcall_extr(early);
initcall_extr(kernel);

/* Early initcalls are used for early system
 * initialization in a way that is required by
 * a specific architecture we are targeting. */
#define initcall_early(id, fn) \
    initcall_link(id, fn); \
    initcall_depn(id, early); \
    initcall_depn(kernel, id)

/* Kernel initcalls are used for the second
 * initialization step, at this point system
 * must have setup a basic driver to print stuff
 * into and is ready for cross-platform setup */
#define initcall_kernel(id, fn) \
    initcall_link(id, fn); \
    initcall_depn(id, kernel)

/* Generated by a shell script */
extern const initcall_t initcalls[];

#endif
