/* SPDX-License-Identifier: BSD-2-Clause */
#ifndef _SYS_INIT_H_
#define _SYS_INIT_H_ 1
#include <sys/cdefs.h>

typedef int(*initcall_t)(void);

#define initcall_extr(id) \
    int __initcall_##id(void)

#define initcall_link(id, fn) \
    int __initcall_##id(void) __alias(fn)

#define initcall_func(id) \
    int __initcall_##id(void)

#define initcall_depn(id, dp) \
    static const initcall_t __used __section(".discard.init.test") \
        __concat(__test_initcall, __COUNTER__) = &__initcall_##dp, \
        __concat(__test_initcall, __COUNTER__) = &__initcall_##id; \
    static const char __used __section(".discard.init.depn") __aligned(1) \
        __concat(__depn_initcall, __COUNTER__)[] = #dp " " #id

/* TODO: add more stub initcalls */
initcall_extr(early);

/* Used for early system initialization such
 * as basic I/O drivers and target-specific subsystems
 * without which the system shits itself. */
#define initcall_early(id, fn) \
    initcall_link(id, fn); \
    initcall_depn(id, early)

/* Generated by a shell script */
extern const initcall_t initcalls[];

#endif
